export const FPS = 30;
export const slides = [
  {kind:'hero', seconds:15, label:'VISIBILIDAD DE RED', title:'Tus datos salen.\n¿Sabés adónde?', subtitle:'TRACE hace visible el recorrido de tus conexiones.', note:'Todos los días nuestros dispositivos se conectan a servicios que no vemos. Cuando aparece una conexión desconocida, surge una pregunta simple: ¿adónde están yendo mis datos? TRACE nace para hacer visible ese recorrido y ayudarnos a entender qué merece nuestra atención.'},
  {kind:'problem', seconds:20, label:'EL PROBLEMA', title:'Una conexión sin contexto\nes una pregunta sin respuesta.', subtitle:'¿Qué dispositivo? ¿Qué destino? ¿Qué cambió?', note:'Una dirección IP o una lista de paquetes no explican por sí solas qué está pasando. Para investigar necesitamos relacionar el dispositivo, el destino y el evento. Nuestra hipótesis es que reunir ese contexto en una vista comprensible puede ayudar a decidir qué revisar primero.'},
  {kind:'map', seconds:25, label:'LA PROPUESTA', title:'El recorrido, en una sola vista.', subtitle:'Dispositivo, destino y ruta conectados visualmente.', note:'Esta es la propuesta de TRACE: un mapa de conexiones con un inspector que reúne origen, destino, protocolo y ruta. El prototipo permite explorar ese lenguaje visual tanto en escritorio como en móvil. Todo el tráfico que mostramos hoy es simulado: estamos presentando la experiencia, todavía no una herramienta conectada a una red real.'},
  {kind:'flow', seconds:25, label:'DEMO · EXPLORAR', title:'Cada flujo tiene una historia.', subtitle:'Elegí una conexión y entendé su contexto.', note:'En la demo seleccionamos un flujo. Podemos ver de qué dispositivo sale, hacia dónde se dirige y los saltos representados en su recorrido. La interfaz también distingue rutas observadas, inferidas o desconocidas. Esa distinción forma parte del diseño: en el producto tendremos que validar qué podemos medir y con qué confianza, sin prometer visibilidad que no tenemos.'},
  {kind:'alert', seconds:25, label:'DEMO · INVESTIGAR', title:'Una alerta abre\nla investigación.', subtitle:'Nuevo destino → dispositivo → flujo asociado.', note:'Ahora aparece una alerta por un destino nuevo. En lugar de quedarse en una notificación aislada, la demo permite abrir el flujo asociado y recuperar su contexto. Un destino desconocido no demuestra un ataque: es una señal para investigar. Las alertas y los controles de esta pantalla son demostrativos; todavía no detectan ni bloquean tráfico real.'},
  {kind:'focus', seconds:20, label:'PRIMER USUARIO · HIPÓTESIS', title:'Empezar por quien\nnecesita investigar.', subtitle:'Responsables de redes pequeñas y equipos técnicos.', note:'Proponemos empezar con responsables de redes pequeñas y equipos técnicos que necesitan investigar conexiones. El caso inicial es concreto: identificar qué dispositivo originó una conexión y revisar el destino. Antes de ampliar el producto, queremos comprobar si esta experiencia les resulta comprensible y si reduce el tiempo necesario para encontrar ese contexto.'},
  {kind:'status', seconds:20, label:'ESTADO DEL PROYECTO', title:'Una experiencia que ya\npodemos poner a prueba.', subtitle:'Prototipo navegable en escritorio y móvil.', note:'Hoy tenemos un prototipo navegable con mapa, detalle de flujos, dispositivos y alertas. Los dispositivos y las capas se guardan localmente. El siguiente hito es incorporar captura real en un entorno controlado y con consentimiento. También faltan backend y autenticación. Esa separación nos permite mostrar lo construido y enfocar con claridad el próximo experimento.'},
  {kind:'next', seconds:20, label:'PRÓXIMO EXPERIMENTO', title:'Validar con una red real.', subtitle:'Capturar. Interpretar. Medir.', note:'El próximo experimento tiene tres pasos: obtener metadatos de conexiones en una red de prueba autorizada, relacionarlos con dispositivos y destinos, y medir si los usuarios resuelven una investigación con mayor claridad. Mediremos tiempo hasta identificar el contexto, comprensión de las rutas y utilidad de las alertas. Son criterios propuestos; todavía no tenemos resultados de un piloto.'},
  {kind:'close', seconds:10, label:'TRACE', title:'Ver el recorrido.\nEntender la conexión.', subtitle:'Buscamos un entorno piloto y usuarios para validarlo.', note:'TRACE quiere convertir conexiones invisibles en preguntas que podamos responder. Ya podemos probar la experiencia. Buscamos un entorno piloto y usuarios para validar el siguiente paso con tráfico real. Ver el recorrido. Entender la conexión.'}
] as const;
export const starts = slides.map((_, i) => slides.slice(0,i).reduce((sum,s)=>sum+s.seconds*FPS,0));
export const durationInFrames = slides.reduce((sum,s)=>sum+s.seconds*FPS,0);
