import React,{useRef,useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Player,PlayerRef} from '@remotion/player';
import {Deck} from './Deck';
import {slides,starts,durationInFrames,FPS} from './content';
import './style.css';
function App(){
 const player=useRef<PlayerRef>(null);const [index,setIndex]=useState(0); const [notes,setNotes]=useState(false); const [playing,setPlaying]=useState(false);
 const jump=(i:number)=>{const next=Math.max(0,Math.min(slides.length-1,i));player.current?.pause();player.current?.seekTo(starts[next]+30);setIndex(next);};
 useEffect(()=>{const p=player.current;if(!p)return; p.seekTo(30); const frame=({detail}:{detail:{frame:number}})=>setIndex(Math.max(0,starts.findLastIndex(s=>s<=detail.frame))); const play=()=>setPlaying(true);const pause=()=>setPlaying(false);p.addEventListener('frameupdate',frame);p.addEventListener('play',play);p.addEventListener('pause',pause);return()=>{p.removeEventListener('frameupdate',frame);p.removeEventListener('play',play);p.removeEventListener('pause',pause);};},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(['INPUT','TEXTAREA'].includes((e.target as HTMLElement).tagName))return;if(e.key===' '&&(e.target as HTMLElement).tagName==='BUTTON')return;if(e.key==='ArrowRight'){e.preventDefault();jump(index+1)}if(e.key==='ArrowLeft'){e.preventDefault();jump(index-1)}if(e.key===' '){e.preventDefault();player.current?.toggle()}if(e.key.toLowerCase()==='n')setNotes(v=>!v);if(e.key.toLowerCase()==='f')player.current?.requestFullscreen();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[index]);
 return <main><header><strong>TRACE</strong><span>Pitch · 3 minutos · 9 escenas</span><span className="links"><a href="/TRACE-deck.pdf">Deck PDF</a><a href="/TRACE-guion.txt">Guion</a></span></header><Player ref={player} component={Deck} durationInFrames={durationInFrames} compositionWidth={1920} compositionHeight={1080} fps={FPS} style={{width:'100%',aspectRatio:'16 / 9'}} controls={false}/><nav aria-label="Controles de presentación"><button disabled={index===0} onClick={()=>jump(index-1)}>← Anterior</button><span>{index+1} / {slides.length}</span><button disabled={index===slides.length-1} onClick={()=>jump(index+1)}>Siguiente →</button><button onClick={()=>player.current?.toggle()}>{playing?'Pausar':'Reproducir'}</button><button onClick={()=>player.current?.requestFullscreen()}>Pantalla completa</button><button aria-pressed={notes} onClick={()=>setNotes(!notes)}>Guion</button></nav>{notes&&<aside><h2>{slides[index].label} · {slides[index].seconds} s</h2><p>{slides[index].note}</p><a href="https://github.com/mindsetwhite/TRACE-FIE-HACKATON-P">Fuente: repositorio TRACE</a></aside>}<footer>← → escenas · Espacio reproducir/pausar · F pantalla completa · N guion. Datos de demostración.</footer></main>
}createRoot(document.getElementById('root')!).render(<App/>);
